In [27]:
import numpy as np
import pandas as pd
df=pd.read_csv("D:\datascience/diabetes.csv")
print(df)

     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                  

In [28]:
x=df.iloc[:,:-1].values #.values used print array
print(x)

[[  6.    148.     72.    ...  33.6     0.627  50.   ]
 [  1.     85.     66.    ...  26.6     0.351  31.   ]
 [  8.    183.     64.    ...  23.3     0.672  32.   ]
 ...
 [  5.    121.     72.    ...  26.2     0.245  30.   ]
 [  1.    126.     60.    ...  30.1     0.349  47.   ]
 [  1.     93.     70.    ...  30.4     0.315  23.   ]]


In [29]:
y=df.iloc[:,-1].values
print(y)

[1 0 1 0 1 0 1 0 1 1 0 1 0 1 1 1 1 1 0 1 0 0 1 1 1 1 1 0 0 0 0 1 0 0 0 0 0
 1 1 1 0 0 0 1 0 1 0 0 1 0 0 0 0 1 0 0 1 0 0 0 0 1 0 0 1 0 1 0 0 0 1 0 1 0
 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 1 1
 1 0 0 1 1 1 0 0 0 1 0 0 0 1 1 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0
 0 0 0 0 1 0 1 1 0 0 0 1 0 0 0 0 1 1 0 0 0 0 1 1 0 0 0 1 0 1 0 1 0 0 0 0 0
 1 1 1 1 1 0 0 1 1 0 1 0 1 1 1 0 0 0 0 0 0 1 1 0 1 0 0 0 1 1 1 1 0 1 1 1 1
 0 0 0 0 0 1 0 0 1 1 0 0 0 1 1 1 1 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0
 1 0 1 0 0 1 0 1 0 0 1 1 0 0 0 0 0 1 0 0 0 1 0 0 1 1 0 0 1 0 0 0 1 1 1 0 0
 1 0 1 0 1 1 0 1 0 0 1 0 1 1 0 0 1 0 1 0 0 1 0 1 0 1 1 1 0 0 1 0 1 0 0 0 1
 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 1 1 0 1 1 0 0 1 0 0 1 0 0 1
 1 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 1 1 1 0 0 1 0 0 1 0 0 1 0 1 1 0 1 0 1 0 1
 0 1 1 0 0 0 0 1 1 0 1 0 1 0 0 0 0 1 1 0 1 0 1 0 0 0 0 0 1 0 0 0 0 1 0 0 1
 1 1 0 0 1 0 0 1 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 1
 0 0 0 1 1 0 0 0 0 0 0 0 

In [30]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=1)
print(x_train)

[[1.50e+01 1.36e+02 7.00e+01 ... 3.71e+01 1.53e-01 4.30e+01]
 [0.00e+00 9.70e+01 6.40e+01 ... 3.68e+01 6.00e-01 2.50e+01]
 [1.00e+00 1.16e+02 7.00e+01 ... 2.74e+01 2.04e-01 2.10e+01]
 ...
 [1.30e+01 1.26e+02 9.00e+01 ... 4.34e+01 5.83e-01 4.20e+01]
 [4.00e+00 1.71e+02 7.20e+01 ... 4.36e+01 4.79e-01 2.60e+01]
 [9.00e+00 1.02e+02 7.60e+01 ... 3.29e+01 6.65e-01 4.60e+01]]


In [31]:
print(y_train)

[1 0 0 0 0 0 0 1 0 1 0 0 1 0 0 1 0 0 0 0 1 0 1 0 0 0 0 1 1 0 0 0 0 1 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 0 1 0 0 0
 1 1 0 1 0 0 1 1 1 0 0 1 0 1 1 0 1 1 0 0 1 1 1 0 1 0 0 1 0 1 0 0 0 0 0 1 1
 1 0 0 0 0 1 1 0 0 0 0 0 1 1 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 1 0 0 0 1 1 0 1
 0 0 0 1 0 0 0 1 1 0 0 1 0 0 0 0 0 0 0 0 1 0 1 0 1 0 1 0 0 0 0 0 0 1 0 1 1
 0 1 1 1 0 1 0 0 1 1 0 1 1 1 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0
 0 0 1 0 1 0 0 0 0 0 0 0 0 0 1 0 1 0 0 1 1 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 1
 1 0 0 0 0 0 0 1 0 1 1 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 1 0 0 1 1 0 0 1 0 0 0
 0 0 0 1 0 0 0 1 1 0 1 1 1 0 0 0 0 1 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0
 0 0 0 0 0 1 0 0 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 0 0 0 0 1 1 1 0 0 0 0 1 1
 1 1 1 1 1 0 0 0 1 0 0 0 0 1 0 1 0 0 1 0 0 1 0 0 0 0 0 1 0 1 0 1 0 1 0 0 0
 1 0 1 1 0 0 1 1 0 0 0 1 1 0 0 1 1 0 0 1 0 0 0 1 0 0 0 1 1 0 0 0 0 0 0 0 0
 0 0 0 1 1 0 0 0 1 0 1 0 1 0 0 0 1 0 1 1 1 1 0 0 0 1 0 0 0 0 0 1 0 1 1 0 0
 0 0 1 1 1 0 1 0 1 0 1 0 

In [32]:
print(x_test)

[[  7.    136.     74.    ...  26.      0.647  51.   ]
 [  1.    151.     60.    ...  26.1     0.179  22.   ]
 [  6.    109.     60.    ...  25.      0.206  27.   ]
 ...
 [  1.     91.     54.    ...  25.2     0.234  23.   ]
 [ 10.    168.     74.    ...  38.      0.537  34.   ]
 [  9.    112.     82.    ...  34.2     0.26   36.   ]]


In [33]:
print(y_test)

[0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 1 0 0 0 1 1 1 1 0 0 0 1 0 1 1 0 0 1 0 1 0
 0 0 0 0 0 0 1 0 0 1 1 0 1 0 0 1 0 1 0 1 0 0 0 0 0 1 0 1 0 1 1 0 1 1 0 0 0
 1 1 1 0 0 1 1 0 1 1 0 0 1 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 1 0 1 0 1
 0 0 0 1 0 0 1 0 1 0 1 1 0 0 0 0 1 0 0 1 0 1 0 0 0 0 0 1 0 1 0 0 1 1 1 0 0
 1 0 0 1 0 0 1 1 0 0 0 0 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 0 1 0 0 0 1 0 0 1 0
 0 0 0 1 0 0 0 0 0 1 0 0 0 1 1 1 0 0 0 1 1 0 0 0 1 0 0 1 1 0 1 1 0 0 1 0 0
 0 1 1 0 0 0 0 1 1]


In [34]:
from sklearn.preprocessing import StandardScaler
scalar=StandardScaler()
scalar.fit(x_train)
x_train=scalar.transform(x_train)
x_test=scalar.transform(x_test)


In [35]:
print(x_train)

[[ 3.3536084   0.48047259  0.05216975 ...  0.68611992 -0.94690147
   0.81020454]
 [-1.12101735 -0.76891126 -0.2463932  ...  0.64699564  0.39612987
  -0.69526203]
 [-0.82270897 -0.16023707  0.05216975 ... -0.5788985  -0.7936697
  -1.02981015]
 ...
 [ 2.75699163  0.16011776  1.04737957 ...  1.50772982  0.34505262
   0.72656751]
 [ 0.07221618  1.60171451  0.15169073 ...  1.53381267  0.03258
  -0.611625  ]
 [ 1.5637581  -0.60873384  0.3507327  ...  0.13837998  0.59142526
   1.06111563]]


In [36]:
print(x_test)

[[ 0.96714133  0.48047259  0.25121172 ... -0.76147848  0.53734346
   1.47930079]
 [-0.82270897  0.96100484 -0.44543516 ... -0.74843705 -0.86878331
  -0.94617312]
 [ 0.66883295 -0.38448546 -0.44543516 ... -0.89189275 -0.78766061
  -0.52798796]
 ...
 [-0.82270897 -0.96112415 -0.74399811 ... -0.8658099  -0.70353337
  -0.86253609]
 [ 1.86206648  1.50560806  0.25121172 ...  0.80349276  0.20684358
   0.05747126]
 [ 1.5637581  -0.28837901  0.64929565 ...  0.30791853 -0.62541522
   0.22474532]]


In [38]:
from sklearn.svm import SVC
classifier=SVC()
classifier.fit(x_train,y_train)
y_pred=classifier.predict(x_test)
print(classifier.predict([[6,148,72,22,5,0,35,60]]))

[0]


In [39]:
from sklearn.metrics import accuracy_score
score=accuracy_score(y_pred,y_test)
print(score)

0.7922077922077922
