In [3]:
import numpy as np
import pandas as pd
df=pd.read_csv("D:\datascience\Fish.csv")
df

Species  Weight  Length1  Length2  Length3   Height   Width
0     Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1     Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2     Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3     Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4     Bream   430.0     26.5     29.0     34.0  12.4440  5.1340
..      ...     ...      ...      ...      ...      ...     ...
154   Smelt    12.2     11.5     12.2     13.4   2.0904  1.3936
155   Smelt    13.4     11.7     12.4     13.5   2.4300  1.2690
156   Smelt    12.2     12.1     13.0     13.8   2.2770  1.2558
157   Smelt    19.7     13.2     14.3     15.2   2.8728  2.0672
158   Smelt    19.9     13.8     15.0     16.2   2.9322  1.8792

[159 rows x 7 columns]

In [4]:
df.head()

Species  Weight  Length1  Length2  Length3   Height   Width
0   Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1   Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2   Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3   Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4   Bream   430.0     26.5     29.0     34.0  12.4440  5.1340

In [5]:
df.isna().sum()

Species    0
Weight     0
Length1    0
Length2    0
Length3    0
Height     0
Width      0
dtype: int64

In [6]:
df.describe

<bound method NDFrame.describe of     Species  Weight  Length1  Length2  Length3   Height   Width
0     Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1     Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2     Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3     Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4     Bream   430.0     26.5     29.0     34.0  12.4440  5.1340
..      ...     ...      ...      ...      ...      ...     ...
154   Smelt    12.2     11.5     12.2     13.4   2.0904  1.3936
155   Smelt    13.4     11.7     12.4     13.5   2.4300  1.2690
156   Smelt    12.2     12.1     13.0     13.8   2.2770  1.2558
157   Smelt    19.7     13.2     14.3     15.2   2.8728  2.0672
158   Smelt    19.9     13.8     15.0     16.2   2.9322  1.8792

[159 rows x 7 columns]>

In [7]:
df.shape

(159, 7)

In [8]:
df.columns

Index(['Species', 'Weight', 'Length1', 'Length2', 'Length3', 'Height',
       'Width'],
      dtype='object')

In [9]:
df['Species'].value_counts()

Perch        56
Bream        35
Roach        20
Pike         17
Smelt        14
Parkki       11
Whitefish     6
Name: Species, dtype: int64

In [10]:
y=df.iloc[:,:1]
y.head()

Species
0   Bream
1   Bream
2   Bream
3   Bream
4   Bream

In [11]:
x=df.iloc[:,1:]
x.head()

Weight  Length1  Length2  Length3   Height   Width
0   242.0     23.2     25.4     30.0  11.5200  4.0200
1   290.0     24.0     26.3     31.2  12.4800  4.3056
2   340.0     23.9     26.5     31.1  12.3778  4.6961
3   363.0     26.3     29.0     33.5  12.7300  4.4555
4   430.0     26.5     29.0     34.0  12.4440  5.1340

In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=1)
x_train.head()

Weight  Length1  Length2  Length3   Height   Width
53    272.0     25.0     27.0     30.6   8.5680  4.7736
117   650.0     36.5     39.0     41.4  11.1366  6.0030
136   540.0     40.1     43.0     45.8   7.7860  5.1296
17    700.0     30.4     33.0     38.5  14.9380  5.1975
77    100.0     16.2     18.0     19.2   5.2224  3.3216

In [13]:
x_test.head()

Weight  Length1  Length2  Length3   Height   Width
29  1000.0     33.5     37.0     42.6  18.9570  6.6030
42   120.0     19.4     21.0     23.7   6.1146  3.2943
14   600.0     29.4     32.0     37.2  14.9544  5.1708
91   130.0     20.5     22.5     24.0   5.8560  3.6240
81    85.0     18.2     20.0     21.0   5.0820  2.7720

In [14]:
y_train.head()

Species
53    Roach
117   Perch
136    Pike
17    Bream
77    Perch

In [15]:
y_test.head()

Species
29   Bream
42   Roach
14   Bream
91   Perch
81   Perch

In [146]:
from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier(n_neighbors=5)
classifier.fit(x_train,y_train)

C:\Users\NIKHIL K\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neighbors\_classification.py:207: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier()

In [147]:
y_pred=classifier.predict(x_test)
print(y_pred)

['Perch' 'Perch' 'Bream' 'Perch' 'Perch' 'Bream' 'Parkki' 'Bream' 'Smelt'
 'Parkki' 'Perch' 'Parkki' 'Smelt' 'Bream' 'Perch' 'Perch' 'Parkki'
 'Bream' 'Bream' 'Perch' 'Smelt' 'Parkki' 'Perch' 'Bream' 'Perch' 'Bream'
 'Bream' 'Smelt' 'Pike' 'Parkki' 'Perch' 'Bream' 'Perch' 'Pike' 'Pike'
 'Bream' 'Roach' 'Perch' 'Perch' 'Roach' 'Bream' 'Bream' 'Bream' 'Smelt'
 'Bream' 'Perch' 'Parkki' 'Perch']


In [148]:
print(classifier.predict([[242,23.2,25.4,30.0,11.5200,4.0200]]))

['Perch']


C:\Users\NIKHIL K\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


In [152]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
result=confusion_matrix(y_test,y_pred)
result1=accuracy_score(y_test,y_pred)
result2=classification_report(y_test,y_pred)
print(result)
print(result1)
print(result2)

[[7 0 3 0 0 0 0]
 [0 1 1 0 0 0 0]
 [6 4 9 0 0 1 0]
 [1 0 0 2 0 0 0]
 [1 2 2 0 1 1 0]
 [0 0 0 0 0 3 0]
 [0 0 1 1 1 0 0]]
0.4791666666666667
              precision    recall  f1-score   support

       Bream       0.47      0.70      0.56        10
      Parkki       0.14      0.50      0.22         2
       Perch       0.56      0.45      0.50        20
        Pike       0.67      0.67      0.67         3
       Roach       0.50      0.14      0.22         7
       Smelt       0.60      1.00      0.75         3
   Whitefish       0.00      0.00      0.00         3

    accuracy                           0.48        48
   macro avg       0.42      0.49      0.42        48
weighted avg       0.49      0.48      0.46        48



C:\Users\NIKHIL K\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\NIKHIL K\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\NIKHIL K\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf