In [50]:
import numpy as np
import pandas as pd
df=pd.read_csv("D:\datascience/lung_cancer_examples.csv")
print(df)

           Name      Surname  Age  Smokes  AreaQ  Alkhol  Result
0          John         Wick   35       3      5       4       1
1          John  Constantine   27      20      2       5       1
2        Camela     Anderson   30       0      5       2       0
3          Alex       Telles   28       0      8       1       0
4         Diego     Maradona   68       4      5       6       1
5     Cristiano      Ronaldo   34       0     10       0       0
6        Mihail          Tal   58      15     10       0       0
7         Kathy        Bates   22      12      5       2       0
8        Nicole       Kidman   45       2      6       0       0
9           Ray      Milland   52      18      4       5       1
10      Fredric        March   33       4      8       0       0
11          Yul      Brynner   18      10      6       3       0
12         Joan     Crawford   25       2      5       1       0
13         Jane        Wyman   28      20      2       8       1
14         Anna      Magn

In [51]:
df=df.drop(['Name','Surname'],axis=1)
print(df)

    Age  Smokes  AreaQ  Alkhol  Result
0    35       3      5       4       1
1    27      20      2       5       1
2    30       0      5       2       0
3    28       0      8       1       0
4    68       4      5       6       1
5    34       0     10       0       0
6    58      15     10       0       0
7    22      12      5       2       0
8    45       2      6       0       0
9    52      18      4       5       1
10   33       4      8       0       0
11   18      10      6       3       0
12   25       2      5       1       0
13   28      20      2       8       1
14   34      25      4       8       1
15   39      18      8       1       0
16   42      22      3       5       1
17   19      12      8       0       0
18   62       5      4       3       1
19   73      10      7       6       1
20   55      15      1       3       1
21   33       8      8       1       0
22   22      20      6       2       0
23   44       5      8       1       0
24   77       3      2   

In [52]:
x=df.iloc[:,:-1].values
print(x)

[[35  3  5  4]
 [27 20  2  5]
 [30  0  5  2]
 [28  0  8  1]
 [68  4  5  6]
 [34  0 10  0]
 [58 15 10  0]
 [22 12  5  2]
 [45  2  6  0]
 [52 18  4  5]
 [33  4  8  0]
 [18 10  6  3]
 [25  2  5  1]
 [28 20  2  8]
 [34 25  4  8]
 [39 18  8  1]
 [42 22  3  5]
 [19 12  8  0]
 [62  5  4  3]
 [73 10  7  6]
 [55 15  1  3]
 [33  8  8  1]
 [22 20  6  2]
 [44  5  8  1]
 [77  3  2  6]
 [21 20  5  3]
 [37 15  6  2]
 [34 12  8  0]
 [55 20  1  4]
 [40 20  2  7]
 [36 13  5  2]
 [56 20  3  3]
 [47 15  1  8]
 [62 25  3  4]
 [26 10  7  2]
 [25 20  8  2]
 [59 20  3  4]
 [62 15  5  5]
 [33 25  8  2]
 [37 10  5  3]
 [50 20  2  4]
 [47 12  8  0]
 [69 20  5  4]
 [63 20  4  5]
 [39 15  7  2]
 [21 20  8  3]
 [31 20  9  4]
 [28 10  4  1]
 [53 20  6  3]
 [62 20  5  6]
 [42 12  6  2]
 [44 30  1  6]
 [26 34  1  8]
 [35 20  5  1]
 [26 13  6  1]
 [77 20  5  4]
 [75 15  3  5]
 [43 30  3  8]
 [51 25  9  0]]


In [53]:
y=df.iloc[:,-1].values
print(y)

[1 1 0 0 1 0 0 0 0 1 0 0 0 1 1 0 1 0 1 1 1 0 0 0 1 0 0 0 1 1 0 1 1 1 0 0 1
 1 0 0 1 0 1 1 0 0 0 0 1 1 0 1 1 0 0 1 1 1 0]


In [54]:
from collections import Counter
print("the number of classess",Counter(y))

the number of classess Counter({0: 31, 1: 28})


In [55]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=1)

In [56]:
print(df.describe())

             Age     Smokes      AreaQ     Alkhol     Result
count  59.000000  59.000000  59.000000  59.000000  59.000000
mean   42.627119  15.067797   5.203390   3.237288   0.474576
std    16.235230   7.984607   2.461984   2.380517   0.503640
min    18.000000   0.000000   1.000000   0.000000   0.000000
25%    29.000000  10.000000   3.000000   1.000000   0.000000
50%    39.000000  15.000000   5.000000   3.000000   0.000000
75%    55.000000  20.000000   7.500000   5.000000   1.000000
max    77.000000  34.000000  10.000000   8.000000   1.000000


In [57]:
from sklearn import preprocessing
from sklearn.preprocessing import MinMaxScaler
import numpy as np
MinMaxScaler=preprocessing.MinMaxScaler()
x_train=MinMaxScaler.fit_transform(x_train)
x_test=MinMaxScaler.fit_transform(x_test)
print(x_test)

[[0.71153846 0.58823529 0.57142857 0.75      ]
 [0.09615385 0.         0.57142857 0.25      ]
 [0.         0.58823529 1.         0.25      ]
 [0.05769231 0.29411765 0.42857143 0.125     ]
 [0.23076923 0.29411765 0.57142857 0.375     ]
 [0.01923077 0.29411765 0.85714286 0.25      ]
 [0.15384615 0.73529412 1.         0.25      ]
 [0.92307692 0.29411765 0.85714286 0.75      ]
 [0.15384615 0.23529412 1.         0.125     ]
 [0.01923077 1.         0.         1.        ]
 [0.26923077 0.44117647 0.85714286 0.25      ]
 [0.05769231 0.         1.         0.125     ]
 [0.65384615 0.58823529 0.28571429 0.5       ]
 [0.48076923 0.58823529 0.14285714 0.5       ]
 [1.         0.08823529 0.14285714 0.75      ]
 [0.15384615 0.11764706 1.         0.        ]
 [0.36538462 0.88235294 0.         0.75      ]
 [0.23076923 0.44117647 0.71428571 0.25      ]]


In [58]:
print(x_test)

[[0.71153846 0.58823529 0.57142857 0.75      ]
 [0.09615385 0.         0.57142857 0.25      ]
 [0.         0.58823529 1.         0.25      ]
 [0.05769231 0.29411765 0.42857143 0.125     ]
 [0.23076923 0.29411765 0.57142857 0.375     ]
 [0.01923077 0.29411765 0.85714286 0.25      ]
 [0.15384615 0.73529412 1.         0.25      ]
 [0.92307692 0.29411765 0.85714286 0.75      ]
 [0.15384615 0.23529412 1.         0.125     ]
 [0.01923077 1.         0.         1.        ]
 [0.26923077 0.44117647 0.85714286 0.25      ]
 [0.05769231 0.         1.         0.125     ]
 [0.65384615 0.58823529 0.28571429 0.5       ]
 [0.48076923 0.58823529 0.14285714 0.5       ]
 [1.         0.08823529 0.14285714 0.75      ]
 [0.15384615 0.11764706 1.         0.        ]
 [0.36538462 0.88235294 0.         0.75      ]
 [0.23076923 0.44117647 0.71428571 0.25      ]]


In [59]:
from sklearn.preprocessing import StandardScaler
scalar=StandardScaler()
scalar.fit(x_train)
x_train=scalar.transform(x_train)
x_test=scalar.transform(x_test)
print(x_train)

[[ 2.09039124  0.63995837 -0.07059551  0.31279639]
 [-0.45226265 -0.35284191 -0.07059551 -0.51460051]
 [ 0.22991278 -0.49467052  1.16986852 -1.34199741]
 [ 0.60200847  0.63995837  0.3428925  -0.10090206]
 [-0.57629454 -0.49467052  1.16986852 -1.34199741]
 [-0.76234239  0.63995837  1.58335653  0.31279639]
 [-0.01815101  2.05824449 -0.89757154  1.96759018]
 [ 0.78805632  0.63995837 -0.89757154 -0.10090206]
 [-0.94839023  0.63995837 -1.31105955  1.96759018]
 [-1.32048593  0.63995837  0.3428925  -0.51460051]
 [-0.08016696 -0.49467052  0.3428925  -0.51460051]
 [ 0.22991278 -0.06918469 -1.72454756  1.96759018]
 [-1.50653377 -0.49467052  1.16986852 -1.34199741]
 [-1.07242213 -0.35284191  0.3428925  -0.92829896]
 [ 1.16015201  1.34910143 -0.89757154  0.31279639]
 [ 0.04386494 -1.48747081  1.16986852 -0.92829896]
 [ 1.5322477  -1.62929942 -0.07059551  1.14019328]
 [-0.57629454  1.34910143 -0.48408353  1.96759018]
 [-0.20419885  0.63995837 -1.31105955  1.55389173]
 [ 0.72604037  0.63995837 -1.72

In [60]:
print(x_test)

[[ 1.0349275   0.30624399  0.40196221  1.14019328]
 [-1.21672847 -2.19661387  0.40196221 -0.51460051]
 [-1.56854972  0.30624399  1.99684454 -0.51460051]
 [-1.35745697 -0.94518494 -0.12966523 -0.92829896]
 [-0.72417873 -0.94518494  0.40196221 -0.10090206]
 [-1.49818547 -0.94518494  1.4652171  -0.51460051]
 [-1.00563573  0.93195845  1.99684454 -0.51460051]
 [ 1.80893424 -0.94518494  1.4652171   1.14019328]
 [-1.00563573 -1.19547072  1.99684454 -0.92829896]
 [-1.49818547  2.05824449 -1.72454756  1.96759018]
 [-0.58345023 -0.31947047  1.4652171  -0.51460051]
 [-1.35745697 -2.19661387  1.99684454 -0.92829896]
 [ 0.82383475  0.30624399 -0.66129267  0.31279639]
 [ 0.19055651  0.30624399 -1.19292012  0.31279639]
 [ 2.09039124 -1.82118519 -1.19292012  1.14019328]
 [-1.00563573 -1.6960423   1.99684454 -1.34199741]
 [-0.23162899  1.55767292 -1.72454756  1.14019328]
 [-0.72417873 -0.31947047  0.93358966 -0.51460051]]


In [61]:
from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier(n_neighbors=5)
classifier.fit(x_train,y_train)

KNeighborsClassifier()

In [62]:
y_pred=classifier.predict(x_test)
print(y_pred)

[1 0 0 0 0 0 0 1 0 1 0 0 1 1 1 0 1 0]


In [64]:
print(classifier.predict([[1,2,6,7]]))

[1]


In [65]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
result=confusion_matrix(y_test,y_pred)
result1=accuracy_score(y_test,y_pred)
print(result)
print(result1)

[[11  0]
 [ 0  7]]
1.0


In [66]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       1.00      1.00      1.00         7

    accuracy                           1.00        18
   macro avg       1.00      1.00      1.00        18
weighted avg       1.00      1.00      1.00        18



In [67]:
from sklearn.naive_bayes import GaussianNB
model=GaussianNB()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
#print(y_pred)
print(model.predict([[2,5,5,6]]))

[1]


In [68]:
from sklearn.metrics import confusion_matrix,accuracy_score
score=accuracy_score(y_pred,y_test)
print(score)

1.0


In [70]:
from sklearn.svm import SVC
classifier=SVC()
classifier.fit(x_train,y_train)
y_pred=classifier.predict(x_test)
print(classifier.predict([[6,148,72,22]]))

[1]


In [71]:
from sklearn.metrics import accuracy_score
score=accuracy_score(y_pred,y_test)
print(score)

1.0
