In [1]:
import numpy as np
import pandas as pd
df=pd.read_csv("D:\datascience/lung_cancer_examples.csv")
df.head()

Name      Surname  Age  Smokes  AreaQ  Alkhol  Result
0    John         Wick   35       3      5       4       1
1    John  Constantine   27      20      2       5       1
2  Camela     Anderson   30       0      5       2       0
3    Alex       Telles   28       0      8       1       0
4   Diego     Maradona   68       4      5       6       1

In [2]:
df=df.drop(['Name','Surname'],axis=1)
df.head()

Age  Smokes  AreaQ  Alkhol  Result
0   35       3      5       4       1
1   27      20      2       5       1
2   30       0      5       2       0
3   28       0      8       1       0
4   68       4      5       6       1

In [3]:
x=df.iloc[:,:-1]
x.head()

Age  Smokes  AreaQ  Alkhol
0   35       3      5       4
1   27      20      2       5
2   30       0      5       2
3   28       0      8       1
4   68       4      5       6

In [4]:
y=df.iloc[:,-1]
y.head()

0    1
1    1
2    0
3    0
4    1
Name: Result, dtype: int64

In [5]:
from collections import Counter
print("the number of classess",Counter(y))

the number of classess Counter({0: 31, 1: 28})


In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=1)

In [7]:
print(df.describe())

             Age     Smokes      AreaQ     Alkhol     Result
count  59.000000  59.000000  59.000000  59.000000  59.000000
mean   42.627119  15.067797   5.203390   3.237288   0.474576
std    16.235230   7.984607   2.461984   2.380517   0.503640
min    18.000000   0.000000   1.000000   0.000000   0.000000
25%    29.000000  10.000000   3.000000   1.000000   0.000000
50%    39.000000  15.000000   5.000000   3.000000   0.000000
75%    55.000000  20.000000   7.500000   5.000000   1.000000
max    77.000000  34.000000  10.000000   8.000000   1.000000


In [8]:
from sklearn import preprocessing
from sklearn.preprocessing import MinMaxScaler
import numpy as np
MinMaxScaler=preprocessing.MinMaxScaler()
x_train=MinMaxScaler.fit_transform(x_train)
x_test=MinMaxScaler.fit_transform(x_test)
print(x_test)

[[0.71153846 0.58823529 0.57142857 0.75      ]
 [0.09615385 0.         0.57142857 0.25      ]
 [0.         0.58823529 1.         0.25      ]
 [0.05769231 0.29411765 0.42857143 0.125     ]
 [0.23076923 0.29411765 0.57142857 0.375     ]
 [0.01923077 0.29411765 0.85714286 0.25      ]
 [0.15384615 0.73529412 1.         0.25      ]
 [0.92307692 0.29411765 0.85714286 0.75      ]
 [0.15384615 0.23529412 1.         0.125     ]
 [0.01923077 1.         0.         1.        ]
 [0.26923077 0.44117647 0.85714286 0.25      ]
 [0.05769231 0.         1.         0.125     ]
 [0.65384615 0.58823529 0.28571429 0.5       ]
 [0.48076923 0.58823529 0.14285714 0.5       ]
 [1.         0.08823529 0.14285714 0.75      ]
 [0.15384615 0.11764706 1.         0.        ]
 [0.36538462 0.88235294 0.         0.75      ]
 [0.23076923 0.44117647 0.71428571 0.25      ]]


In [11]:
x_test

array([[ 1.0349275 ,  0.30624399,  0.40196221,  1.14019328],
       [-1.21672847, -2.19661387,  0.40196221, -0.51460051],
       [-1.56854972,  0.30624399,  1.99684454, -0.51460051],
       [-1.35745697, -0.94518494, -0.12966523, -0.92829896],
       [-0.72417873, -0.94518494,  0.40196221, -0.10090206],
       [-1.49818547, -0.94518494,  1.4652171 , -0.51460051],
       [-1.00563573,  0.93195845,  1.99684454, -0.51460051],
       [ 1.80893424, -0.94518494,  1.4652171 ,  1.14019328],
       [-1.00563573, -1.19547072,  1.99684454, -0.92829896],
       [-1.49818547,  2.05824449, -1.72454756,  1.96759018],
       [-0.58345023, -0.31947047,  1.4652171 , -0.51460051],
       [-1.35745697, -2.19661387,  1.99684454, -0.92829896],
       [ 0.82383475,  0.30624399, -0.66129267,  0.31279639],
       [ 0.19055651,  0.30624399, -1.19292012,  0.31279639],
       [ 2.09039124, -1.82118519, -1.19292012,  1.14019328],
       [-1.00563573, -1.6960423 ,  1.99684454, -1.34199741],
       [-0.23162899,  1.

In [ ]:
from sklearn.preprocessing import StandardScaler
scalar=StandardScaler()
scalar.fit(x_train)
x_train=scalar.transform(x_train)
x_test=scalar.transform(x_test)
x_train

In [60]:
print(x_test)

[[ 1.0349275   0.30624399  0.40196221  1.14019328]
 [-1.21672847 -2.19661387  0.40196221 -0.51460051]
 [-1.56854972  0.30624399  1.99684454 -0.51460051]
 [-1.35745697 -0.94518494 -0.12966523 -0.92829896]
 [-0.72417873 -0.94518494  0.40196221 -0.10090206]
 [-1.49818547 -0.94518494  1.4652171  -0.51460051]
 [-1.00563573  0.93195845  1.99684454 -0.51460051]
 [ 1.80893424 -0.94518494  1.4652171   1.14019328]
 [-1.00563573 -1.19547072  1.99684454 -0.92829896]
 [-1.49818547  2.05824449 -1.72454756  1.96759018]
 [-0.58345023 -0.31947047  1.4652171  -0.51460051]
 [-1.35745697 -2.19661387  1.99684454 -0.92829896]
 [ 0.82383475  0.30624399 -0.66129267  0.31279639]
 [ 0.19055651  0.30624399 -1.19292012  0.31279639]
 [ 2.09039124 -1.82118519 -1.19292012  1.14019328]
 [-1.00563573 -1.6960423   1.99684454 -1.34199741]
 [-0.23162899  1.55767292 -1.72454756  1.14019328]
 [-0.72417873 -0.31947047  0.93358966 -0.51460051]]


In [61]:
from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier(n_neighbors=5)
classifier.fit(x_train,y_train)

KNeighborsClassifier()

In [62]:
y_pred=classifier.predict(x_test)
print(y_pred)

[1 0 0 0 0 0 0 1 0 1 0 0 1 1 1 0 1 0]


In [64]:
print(classifier.predict([[1,2,6,7]]))

[1]


In [65]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
result=confusion_matrix(y_test,y_pred)
result1=accuracy_score(y_test,y_pred)
print(result)
print(result1)

[[11  0]
 [ 0  7]]
1.0


In [66]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       1.00      1.00      1.00         7

    accuracy                           1.00        18
   macro avg       1.00      1.00      1.00        18
weighted avg       1.00      1.00      1.00        18



In [67]:
from sklearn.naive_bayes import GaussianNB
model=GaussianNB()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
#print(y_pred)
print(model.predict([[2,5,5,6]]))

[1]


In [68]:
from sklearn.metrics import confusion_matrix,accuracy_score
score=accuracy_score(y_pred,y_test)
print(score)

1.0


In [70]:
from sklearn.svm import SVC
classifier=SVC()
classifier.fit(x_train,y_train)
y_pred=classifier.predict(x_test)
print(classifier.predict([[6,148,72,22]]))

[1]


In [71]:
from sklearn.metrics import accuracy_score
score=accuracy_score(y_pred,y_test)
print(score)

1.0
