In [19]:
import pandas as pd
import numpy as np
df=pd.read_csv("D:\datascience/advertising.csv")
print(df)

        TV  Radio  Newspaper  Sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3   12.0
3    151.5   41.3       58.5   16.5
4    180.8   10.8       58.4   17.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1   14.0
197  177.0    9.3        6.4   14.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   18.4

[200 rows x 4 columns]


In [20]:
df.describe()

TV       Radio   Newspaper       Sales
count  200.000000  200.000000  200.000000  200.000000
mean   147.042500   23.264000   30.554000   15.130500
std     85.854236   14.846809   21.778621    5.283892
min      0.700000    0.000000    0.300000    1.600000
25%     74.375000    9.975000   12.750000   11.000000
50%    149.750000   22.900000   25.750000   16.000000
75%    218.825000   36.525000   45.100000   19.050000
max    296.400000   49.600000  114.000000   27.000000

In [21]:
df.shape

(200, 4)

In [22]:
print(df.isna().sum())

TV           0
Radio        0
Newspaper    0
Sales        0
dtype: int64


In [23]:
x=df.iloc[:,:-1].values
print(x)

[[230.1  37.8  69.2]
 [ 44.5  39.3  45.1]
 [ 17.2  45.9  69.3]
 [151.5  41.3  58.5]
 [180.8  10.8  58.4]
 [  8.7  48.9  75. ]
 [ 57.5  32.8  23.5]
 [120.2  19.6  11.6]
 [  8.6   2.1   1. ]
 [199.8   2.6  21.2]
 [ 66.1   5.8  24.2]
 [214.7  24.    4. ]
 [ 23.8  35.1  65.9]
 [ 97.5   7.6   7.2]
 [204.1  32.9  46. ]
 [195.4  47.7  52.9]
 [ 67.8  36.6 114. ]
 [281.4  39.6  55.8]
 [ 69.2  20.5  18.3]
 [147.3  23.9  19.1]
 [218.4  27.7  53.4]
 [237.4   5.1  23.5]
 [ 13.2  15.9  49.6]
 [228.3  16.9  26.2]
 [ 62.3  12.6  18.3]
 [262.9   3.5  19.5]
 [142.9  29.3  12.6]
 [240.1  16.7  22.9]
 [248.8  27.1  22.9]
 [ 70.6  16.   40.8]
 [292.9  28.3  43.2]
 [112.9  17.4  38.6]
 [ 97.2   1.5  30. ]
 [265.6  20.    0.3]
 [ 95.7   1.4   7.4]
 [290.7   4.1   8.5]
 [266.9  43.8   5. ]
 [ 74.7  49.4  45.7]
 [ 43.1  26.7  35.1]
 [228.   37.7  32. ]
 [202.5  22.3  31.6]
 [177.   33.4  38.7]
 [293.6  27.7   1.8]
 [206.9   8.4  26.4]
 [ 25.1  25.7  43.3]
 [175.1  22.5  31.5]
 [ 89.7   9.9  35.7]
 [239.9  41.5

In [24]:
y=df.iloc[:,-1].values
print(y)

[22.1 10.4 12.  16.5 17.9  7.2 11.8 13.2  4.8 15.6 12.6 17.4  9.2 13.7
 19.  22.4 12.5 24.4 11.3 14.6 18.  17.5  5.6 20.5  9.7 17.  15.  20.9
 18.9 10.5 21.4 11.9 13.2 17.4 11.9 17.8 25.4 14.7 10.1 21.5 16.6 17.1
 20.7 17.9  8.5 16.1 10.6 23.2 19.8  9.7 16.4 10.7 22.6 21.2 20.2 23.7
  5.5 13.2 23.8 18.4  8.1 24.2 20.7 14.  16.  11.3 11.  13.4 18.9 22.3
 18.3 12.4  8.8 11.  17.   8.7  6.9 14.2  5.3 11.  11.8 17.3 11.3 13.6
 21.7 20.2 12.  16.  12.9 16.7 14.   7.3 19.4 22.2 11.5 16.9 16.7 20.5
 25.4 17.2 16.7 23.8 19.8 19.7 20.7 15.   7.2 12.   5.3 19.8 18.4 21.8
 17.1 20.9 14.6 12.6 12.2  9.4 15.9  6.6 15.5  7.  16.6 15.2 19.7 10.6
  6.6 11.9 24.7  9.7  1.6 17.7  5.7 19.6 10.8 11.6  9.5 20.8  9.6 20.7
 10.9 19.2 20.1 10.4 12.3 10.3 18.2 25.4 10.9 10.1 16.1 11.6 16.6 16.
 20.6  3.2 15.3 10.1  7.3 12.9 16.4 13.3 19.9 18.  11.9 16.9  8.  17.2
 17.1 20.   8.4 17.5  7.6 16.7 16.5 27.  20.2 16.7 16.8 17.6 15.5 17.2
  8.7 26.2 17.6 22.6 10.3 17.3 20.9  6.7 10.8 11.9  5.9 19.6 17.3  7.6
 14.  1

In [25]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=1)
print(x_train)

[[139.2  14.3  25.6]
 [139.3  14.5  10.2]
 [  5.4  29.9   9.4]
 [293.6  27.7   1.8]
 [281.4  39.6  55.8]
 [  8.7  48.9  75. ]
 [ 80.2   0.    9.2]
 [137.9  46.4  59. ]
 [227.2  15.8  49.9]
 [ 31.5  24.6   2.2]
 [262.7  28.8  15.9]
 [213.5  43.   33.8]
 [287.6  43.   71.8]
 [ 11.7  36.9  45.2]
 [ 17.9  37.6  21.6]
 [209.6  20.6  10.7]
 [ 23.8  35.1  65.9]
 [ 76.4   0.8  14.8]
 [250.9  36.5  72.3]
 [141.3  26.8  46.2]
 [187.8  21.1   9.5]
 [134.3   4.9   9.3]
 [239.8   4.1  36.9]
 [224.    2.4  15.6]
 [ 75.5  10.8   6. ]
 [ 97.5   7.6   7.2]
 [ 75.3  20.3  32.5]
 [  8.4  27.2   2.1]
 [191.1  28.7  18.2]
 [175.1  22.5  31.5]
 [135.2  41.7  45.9]
 [266.9  43.8   5. ]
 [ 85.7  35.8  49.3]
 [139.5   2.1  26.6]
 [171.3  39.7  37.7]
 [187.9  17.2  17.9]
 [ 38.2   3.7  13.8]
 [177.    9.3   6.4]
 [ 38.   40.3  11.9]
 [168.4   7.1  12.8]
 [ 16.9  43.7  89.4]
 [237.4   5.1  23.5]
 [ 28.6   1.5  33. ]
 [197.6  23.3  14.2]
 [ 17.2  45.9  69.3]
 [199.1  30.6  38.7]
 [193.2  18.4  65.7]
 [280.7  13.9

In [26]:
#from sklearn.preprocessing import StandardScaler
#scalar=StandardScaler()
#scalar.fit(x_train)
#x_train=scalar.transform(x_train)
#x_test=scalar.transform(x_test)
#print(x_test)

In [27]:
from sklearn.linear_model import LinearRegression
reg=LinearRegression()
reg.fit(x_train,y_train)
y_pred=reg.predict(x_test)
print(y_pred)

[21.28816103 18.04213212 10.0595901  21.08224067 20.76476044 24.47187353
 16.80643646 15.62885738 10.12479884 18.84601896 15.78389695 10.54297035
 18.92928707 15.52557996 17.8412711  15.24120343 13.74212833 21.0643733
 10.05392699 19.26500889 11.16451173 11.97211832  8.61179009 11.98972141
 12.59914023 16.8447954   9.7170889  21.09489946 18.13942474 19.55008709
 22.08796224 17.78527998 16.53883452 14.77303861 21.39458945 16.95491635
 17.22755002 12.31866943 21.04982199  7.77473926  5.38467516  9.63139004
  6.89549204 19.19507436  7.88125192 15.18766673 13.70978421 21.0232936
 20.5350058  20.48867548 24.86087902 14.96304281  7.33545571 19.35630325
 21.32554066 14.7719757  17.19642519  7.11988693 18.30096543  9.65158222]


In [28]:
print(reg.predict([[230.5,37.2,37.6]]))

[21.10115859]


In [33]:
#prnt('intrecept',reg.coef_)
print('interpreter',reg.intercept_)
print('coefficience')
list(zip(x,reg.coef_))

interpreter 4.661439720130813
coefficience


[(array([230.1,  37.8,  69.2]), 0.05502391767315305),
 (array([44.5, 39.3, 45.1]), 0.10251002697521275),
 (array([17.2, 45.9, 69.3]), -0.0015071052925105521)]

In [34]:
from sklearn.metrics import mean_absolute_percentage_error
print("MEAN",mean_absolute_percentage_error(y_test,y_pred))

MEAN 0.07695080788726724


In [38]:
from sklearn.metrics import mean_squared_error
print(mean_squared_error(y_test,y_pred))

2.370659971225658


NameError: name 'mean_absolute_error' is not defined